[env:mkrwifi1010]
platform = atmelsam
board = mkrwifi1010
framework = arduino
monitor_speed = 9600

lib_deps =
    arduino-libraries/WiFiNINA @ ^1.8.14
    arduino-libraries/Arduino_MKRIoTCarrier @ ^2.0.4
    bblanchon/ArduinoJson @ ^6.21.3
    witnessmenow/UniversalTelegramBot @ ^1.3.0