[env:mkrwifi1010]
platform = atmelsam
board = mkrwifi1010
framework = arduino
monitor_speed = 9600


extra_scripts = pre:patch_libs.py

lib_deps =
    WiFiNINA
    Arduino_MKRIoTCarrier
    bblanchon/ArduinoJson @ ^6.21.6
    witnessmenow/UniversalTelegramBot @ ^1.3.0
    ropg/ezTime @ ^0.8.3